Repository openmaptiles/openmaptiles, pull requests merged in 2020-06, with the labels that each got.

#927 Expose MAX_PARALLEL_PSQL to users
  .env
  docker-compose.yml
Labels: trivial

#922 Fix incorrect Imposm config updates
  Makefile
  docker-compose.yml
Labels: bug

#919 aerodrome_label: Remove unused function parameter
  layers/aerodrome_label/aerodrome_label.yaml
  layers/aerodrome_label/layer.sql
Labels: cleanup, trivial

#918 Fix & optimize incorrect function declarations
  layers/aerodrome_label/layer.sql
  layers/aeroway/layer.sql
  layers/boundary/boundary.sql
  layers/building/building.sql
  layers/housenumber/layer.sql
  layers/landcover/landcover.sql
  layers/landuse/landuse.sql
  layers/mountain_peak/layer.sql
  layers/park/layer.sql
  layers/place/city.sql
  layers/place/layer.sql
  layers/poi/layer.sql
  layers/transportation/layer.sql
  layers/transportation_name/layer.sql
  layers/water/water.sql
  layers/water_name/layer.sql
  layers/waterway/waterway.sql
Labels: bug

#936 Build aggregation on zoom level 13
  layers/building/building.sql
  layers/building/building.yaml
  layers/building/etl_diagram.png
  layers/building/mapping.yaml
  layers/building/update_building.sql
Labels: featured
