Repository openmaptiles/openmaptiles, pull requests merged in 2021-11, with the labels that each got.

#1271 Add support for Bus Rapid Transit (highway=busway)
  layers/transportation/class.sql
  layers/transportation/mapping.yaml
  layers/transportation/mapping_diagram.png
  layers/transportation/transportation.yaml
  layers/transportation/update_transportation_merge.sql
  layers/transportation_name/mapping_diagram.png
Labels: schema-change

#1268 Remove empty name_en and name_de values from waterway
  layers/waterway/waterway.sql
Labels: languages

#1284 Document update testing process
  CONTRIBUTING.md
Labels: docs

#1306 add province, increase scalerank + labelrank
  layers/place/mapping.yaml
  layers/place/mapping_diagram.png
  layers/place/place.sql
  layers/place/place.yaml
  layers/place/update_state_point.sql
Labels: layer, schema-change

#1295 BUGFIX: Fix name-based way fragmentation in transportation_name
  layers/transportation/highway_name.sql
  layers/transportation/transportation.yaml
  layers/transportation/update_transportation_merge.sql
  layers/transportation_name/transportation_name.sql
  layers/transportation_name/update_transportation_name.sql
  tests/import/500_import-highway.osm
  tests/test-post-import.sql
  tests/test-post-update.sql
  tests/update/500_update-highway.osc
Labels: enhancement, SQL

#1313 Add expressway tagging to the transportation layer
  layers/transportation/mapping.yaml
  layers/transportation/transportation.sql
  layers/transportation/transportation.yaml
  layers/transportation/update_transportation_merge.sql
  tests/import/500_import-highway.osm
  tests/test-post-import.sql
  tests/test-post-update.sql
  tests/update/500_update-highway.osc
Labels: layer, schema-change

#1281 Use tools v6.1, improve .env docs
  .env
  .github/workflows/performance.yml
Labels: enhancement

#1315 Update openmaptiles.yaml
  openmaptiles.yaml
Labels: docs
