Repository openmaptiles/openmaptiles, pull requests merged in 2021-06, with the labels that each got.

#1085 Switch from amenity=embassy to office=diplomatic #1084
  layers/poi/mapping.yaml
  layers/poi/mapping_diagram.png
Labels: schema-change

#1118 Add notice into README about import-osm
  README.md
Labels: docs

#1129 Update osm_poi_point only on change
  layers/poi/update_poi_point.sql
Labels: SQL, enhancement
