Repository openmaptiles/openmaptiles, pull requests merged in 2021-03, with the labels that each got.

#1088 osm_route_member bugfix
  layers/transportation_name/update_route_member.sql
Labels: bug

#1073 Explicit mention for using `iso_a2` attribute.
  layers/place/place.yaml
Labels: docs

#1093 Update naming convention for networks
  docker-compose.yml
Labels: enhancement

#1096 Improve logging - show BBOX if exists
  Makefile
Labels: docs
